# Generated by Django 5.0.2 on 2024-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id_int',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
